# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33cf53318ffa0f1ff572a0fc8051f516"
name = "Trello Integration"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "/webhooks/orders/update"

[[webhooks.subscriptions]]
topics = ["draft_orders/create"]
uri = "/webhooks/draft-orders/create"

[[webhooks.subscriptions]]
topics = ["draft_orders/update"]
uri = "/webhooks/draft-orders/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_draft_orders,write_draft_orders,read_customers"


[auth]
redirect_urls = [ "https://example.com/api/auth" ]
